#!/usr/bin/env python3
"""Render references/connections.md from config/integrations.json "connections".

One row per data connection (domain | tool | mechanism | auth | write? | last
verified). Connections not verified in >30 days get flagged so credential rot
surfaces before a loop silently breaks.

Usage: python3 scripts/generate-connections.py
The output file is GENERATED — edit config/integrations.json and re-run;
never hand-edit references/connections.md.
"""

import json
import os
from datetime import date, datetime
from pathlib import Path

ROOT = Path(os.environ.get("LAILA_OS_ROOT", Path(__file__).resolve().parent.parent))
SRC = ROOT / "config" / "integrations.json"
OUT = ROOT / "references" / "connections.md"

STALE_DAYS = 30


def main():
    data = json.loads(SRC.read_text())
    conns = data.get("connections", [])
    today = date.today()

    lines = [
        "# Connections Registry",
        "",
        "<!-- GENERATED by scripts/generate-connections.py from config/integrations.json"
        " — do NOT hand-edit. -->",
        "",
        f"Generated: {today.isoformat()}. One row per data connection. "
        "`auth` examples: oauth (stored refresh token), api-key (env var in .env), "
        "browser-session (logged-in automation profile).",
        "",
        "| Domain | Tool | Mechanism | Auth | Write? | Last verified | Reference doc |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]

    stale = []
    for c in conns:
        verified = c.get("last_verified") or "-"
        flag = ""
        if verified != "-":
            age = (today - datetime.strptime(verified, "%Y-%m-%d").date()).days
            if age > STALE_DAYS:
                flag = " (STALE)"
                stale.append((c["tool"], age))
        ref = f"`{c['reference_doc']}`" if c.get("reference_doc") else "-"
        write = "yes" if c.get("can_write") else "read-only"
        lines.append(
            f"| {c['domain']} | {c['tool']} | {c['mechanism']} | {c['auth']} | "
            f"{write} | {verified}{flag} | {ref} |"
        )

    if stale:
        lines += ["", f"## Stale verifications (>{STALE_DAYS} days)", ""]
        lines += [f"- {tool}: {age} days since last verified" for tool, age in stale]
    lines.append("")

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"Wrote {OUT} ({len(conns)} connections, {len(stale)} stale)")


if __name__ == "__main__":
    main()
